ALTER TABLE category
    MODIFY id BIGINT AUTO_INCREMENT NOT NULL ;

ALTER TABLE people
    MODIFY id BIGINT AUTO_INCREMENT NOT NULL ;

ALTER TABLE accounting_entry
    MODIFY id BIGINT AUTO_INCREMENT NOT NULL ;

ALTER TABLE permission
    MODIFY id BIGINT AUTO_INCREMENT NOT NULL ;

ALTER TABLE user
    MODIFY id BIGINT AUTO_INCREMENT NOT NULL ;