ALTER TABLE  category
    MODIFY COLUMN id BIGINT(20) AUTO_INCREMENT;

ALTER TABLE  people
    MODIFY COLUMN id BIGINT(20) AUTO_INCREMENT;

ALTER TABLE  accounting_entry
    MODIFY COLUMN id BIGINT(20) AUTO_INCREMENT;